from django.conf import settings


SIXTEEN_BY_NINE = '16:9'
FOUR_BY_THREE = '4:3'

DEFAULT_ASPECT_RATIOS = (
    (SIXTEEN_BY_NINE, SIXTEEN_BY_NINE),
    (FOUR_BY_THREE, FOUR_BY_THREE),
)

DEFAULT_ASPECT_RATIO = getattr(settings,
        'ARMSTRONG_EMBEDDED_VIDEO_DEFAULT_ASPECT_RATIO', SIXTEEN_BY_NINE)

ASPECT_RATIOS = getattr(settings, 'ARMSTRONG_EMBEDDED_VIDEO_ASPECT_RATIOS',
        DEFAULT_ASPECT_RATIOS)
